/* ============================================================
   IMAGES — HOKA assets as relative file paths under images/.
   Key format: productId, productId_2, productId_3, hero_nyc, hero_trail
   Anything missing falls back to the drawn silhouette.
   ============================================================ */
const IMAGES = {
 clifton11: "images/clifton11-1.jpg",
 clifton11_2: "images/clifton11-2.jpg",
 clifton11_3: "images/clifton11-3.jpg",
 clifton11_4: "images/clifton11-4.jpg",
 hero_nyc: "images/hero-nyc.jpg",
 hero_trail: "images/hero-trail.jpg",
 rockettrail: "images/rockettrail-1.jpg",
 rockettrail_2: "images/rockettrail-2.jpg",
 rockettrail_3: "images/rockettrail-3.jpg",
 arahi8: "images/arahi8-1.jpg",
 arahi8_2: "images/arahi8-2.jpg",
 arahi8_3: "images/arahi8-3.jpg",
 speedgoat: "images/speedgoat-1.jpg",
 speedgoat_2: "images/speedgoat-2.jpg",
 speedgoat_3: "images/speedgoat-3.jpg"
};

const R={first:"Maya",initials:"ME",city:"Brooklyn, NY",age:35,gender:"Women's",
 gait:"Neutral, mild overpronation (left)",assessed:"In store, 12 Mar 2026",
 race:{n:"TCS New York City Marathon",d:"Sun 2 Nov",days:34,goal:"sub-3:45",w:"9°C, light wind"},
 sizes:{shoe:"US 8",width:"Medium",top:"S",bottom:"S"}};
const RACK=[
 {n:"Clifton 10",b:"HOKA",u:"Daily trainer",m:480},{n:"Rocket X 2",b:"HOKA",u:"Race day",m:38},
 {n:"Mach 6",b:"HOKA",u:"Tempo",m:210},{n:"Bondi 9",b:"HOKA",u:"Easy + standing",m:615},
 {n:"Speedgoat 6",b:"HOKA",u:"Trail",m:95},{n:"Ghost 16",b:"Brooks",u:"Daily trainer",m:505},
 {n:"Pegasus 41",b:"Nike",u:"Easy",m:390},{n:"Endorphin Speed 4",b:"Saucony",u:"Tempo",m:240},
 {n:"Novablast 4",b:"ASICS",u:"Easy",m:160},{n:"Cloudmonster",b:"On",u:"Recovery",m:75}];
const EVENTS=[
 {d:"2 NOV",t:"TCS New York City Marathon",x:"Entered · bib 41207"},
 {d:"31 OCT",t:"HOKA race week, 579 Fifth Ave",x:"Shakeout run, engraving, bib pickup"},
 {d:"18 OCT",t:"Brooklyn club long run",x:"32 club members going"},
 {d:"14 MAR",t:"HOKA Project Carbon X",x:"4 km away · entry opens January"}];
const C=[["#0B7FFF","#062A52"],["#FF7A1A","#3A1B05"],["#111827","#4B5563"],["#E5E7EB","#9CA3AF"],["#7C3AED","#2E1065"],["#0F9D58","#06381F"]];

const P={
 clifton11:{n:"Clifton 11",pr:154.95,c:0,cat:"shoes",color:"Rose Cream / Pink",
  r:"The direct successor to the pair you've put 480 miles on. Same fit, more midsole.",
  why:"Built for the three long runs you have left and the taper after them. Your Clifton 10 sits at 480 miles, and the 11 keeps the same last, so there's no adaptation cost this close to race day.",
  desc:"The eleventh season of HOKA's most popular daily trainer. This version brings an elevated engineered mesh upper and a softer open-cell sockliner over the same compression-moulded EVA midsole and smooth MetaRocker geometry. Reflective details and a double-lace lock keep the fit steady on dark morning runs.",
  specs:[["Use","Daily training, easy miles"],["Stack height (women's 8)","38 mm heel / 30 mm forefoot"],["Drop","8 mm"],["Weight (women's 8)","8.18 oz"],["Midsole","Compression-moulded EVA, MetaRocker"],["Outsole","Durabrasion rubber"],["Upper","Engineered mesh, 3D silicone print"]]},
  arahi8:{n:"Arahi 8",pr:150,c:2,cat:"shoes",color:"Rose Cream / Alabaster",
  r:"If your form drifts late in long runs, this guides without the weight penalty.",
  why:"Your gait assessment shows mild overpronation on the left. The H-Frame guides the foot rather than posting under it, so you get support without the brick-like feel of a traditional stability shoe over 42 km.",
  desc:"A stability trainer that combats overpronation using HOKA's H-Frame system rather than a medial post, paired with a jacquard mesh upper and low-profile tooling. This version uses softer materials than the Arahi 7.",
  specs:[["Use","Daily training with support"],["Support","Stabilising H-Frame"],["Stack height (women's)","36.8 mm heel / 29.6 mm forefoot"],["Drop","7.2 mm"],["Weight (women's)","7.72 oz"],["Midsole","Dual-density compression-moulded EVA"],["Outsole","Super-abrasion rubber, podular design"]]},
 rocketx:{n:"Rocket X 2",pr:249.95,c:1,cat:"shoes",color:"Virtual Blue / Swim Day",owned:true,
  r:"Already in your collection at 38 miles. Race-ready.",
  why:"This is your race pair and it's ready — 38 miles in, which is exactly where you want a plated shoe on race morning.",
  desc:"HOKA's marathon racer: a spoon-shaped carbon plate sandwiched between two layers of PEBA foam, in a ProFly X construction built for propulsion over distance.",
  specs:[["Use","Race day, half to marathon"],["Stack height","36 mm heel / 31 mm forefoot"],["Drop","5 mm"],["Weight","7.5 oz (unisex M9)"],["Plate","Spoon-shaped carbon fibre"],["Midsole","PEBA, ProFly X"]]},
  speedgoat:{n:"Speedgoat 6",pr:155,c:5,cat:"shoes",color:"Shifting Sand / Dijon",
  r:"Your trail pair is at 95 miles — a wet course chews through outsole fast.",
  why:"A wet, technical course is the one place outsole compound matters more than cushioning. Vibram Megagrip holds on greasy rock where a road outsole slides out from under you.",
  desc:"HOKA's trail workhorse. A Vibram Megagrip outsole with 5 mm lugs under a cushioned midsole, in an upper built to drain and hold the foot on off-camber ground.",
  specs:[["Use","Technical trail, wet conditions"],["Outsole","Vibram Megagrip"],["Upper","Woven, quick-draining"],["Fit","True to size, roomier toe box"]]},
 rockettrail:{n:"Rocket X Trail",pr:250,c:1,cat:"shoes",color:"Neon Yuzu / Evening Primrose",
  r:"Carbon-plated, max-stack trail racer for runnable ground.",
  why:"If you want to race this rather than survive it, the H-shaped carbon plate and A-TPU foam give you road-shoe propulsion on dirt. Best on runnable terrain — it's a lot of stack for very technical rock.",
  desc:"A carbon-plated trail racer built for speed on dirt, gravel and runnable terrain, with one of the highest stack heights of any trail shoe and a broad ground platform for stability.",
  specs:[["Use","Trail racing, runnable terrain"],["Stack height","45 mm heel / 39 mm forefoot"],["Plate","H-shaped carbon"],["Midsole","A-TPU foam"],["Outsole","Lugged, trail-specific"]]},
 singlet:{n:"Airolite Race Singlet",pr:60,c:3,cat:"apparel",color:"White / Blue Graphite",
  r:"9°C at the Verrazzano start. Light enough to race, cut for layering.",
  why:"At 9°C you'll want something light under a throwaway layer for the corral. This is cut to sit under a long sleeve without bunching at the belt line.",
  desc:"A lightweight, breathable race singlet with a relaxed cut and flat seams at the shoulder.",
  specs:[["Use","Race day, cool conditions"],["Fabric","Recycled polyester, moisture-wicking"],["Fit","Relaxed race cut"]]},
 tights:{n:"Novafly 3\" Short Tight",pr:65,c:2,cat:"apparel",color:"Black",
  r:"Your Chicago race kit, updated. No seams where the belt sits.",
  why:"Same silhouette you raced Chicago in, with the waistband redesigned so a race belt sits above the seam rather than on it.",
  desc:"A 3-inch short tight with a wide, flat waistband and a secure rear pocket.",
  specs:[["Use","Race and tempo"],["Inseam","3 inches"],["Pockets","Rear zip"]]},
 longsleeve:{n:"Glide Long Sleeve",pr:75,c:0,cat:"apparel",color:"Harbor Mist",
  r:"For the three long runs left before taper, at dawn.",
  why:"Your long runs are at dawn in October. This is the layer for 6–11°C that you can push up the arms when you warm.",
  desc:"A mid-weight long sleeve with thumbholes and a dropped hem.",
  specs:[["Use","Cool-weather training"],["Fabric","Brushed knit"],["Details","Thumbholes, reflective trim"]]},
 gloves:{n:"Lightweight Run Glove",pr:30,c:4,cat:"apparel",color:"Black",
  r:"The Staten Island holding pen is cold and long.",
  why:"NYC's start village means two hours outdoors before you run a step. Cheap enough to hand off at the start line.",
  desc:"A thin, touchscreen-compatible knit glove that packs into a pocket.",
  specs:[["Use","Cold starts"],["Fabric","Stretch knit"],["Details","Touchscreen fingertips"]]},
 belt:{n:"Race Belt",pr:35,c:1,cat:"accessories",color:"Black",
  r:"Holds five gels and a phone without bouncing over 42 km.",
  why:"You're carrying eight gels on race day. A belt that doesn't ride up is the difference between taking them and dropping them.",
  desc:"A stretch-woven race belt with gel loops and a zip pocket, worn over or under a layer.",
  specs:[["Use","Race day fuelling"],["Capacity","5 gels + phone"],["Closure","Slide clip"]]},
 chafe:{n:"Anti-Chafe Balm",pr:14,c:5,cat:"accessories",color:"—",
  r:"42 km is a long way to find out you needed this.",
  why:"Nothing to do with performance. It's the single cheapest way to avoid the thing that ruins the last 10 km.",
  desc:"A fragrance-free glide balm for underarms, thighs and bra lines.",
  specs:[["Use","Long runs and racing"],["Size","1.4 oz stick"]]},
 socks:{n:"Crew Run Sock, 3-pack",pr:22,c:3,cat:"accessories",color:"White",
  r:"Race in the pair you've trained in. Buy the spares now.",
  why:"Race-day rule: nothing new. Buying spares of the sock you already run in keeps that true.",
  desc:"A cushioned crew sock with arch support and a seamless toe.",
  specs:[["Use","Training and racing"],["Height","Crew"],["Pack","3 pairs"]]},
 gels:{n:"Energy Gel, 12-pack",pr:36,c:1,cat:"nutrition",color:"Mixed",partner:true,
  r:"Eight for race day, four for the last long run.",
  why:"Practise with the same gel you'll race with. Twelve covers race day plus one long run to test your stomach.",
  desc:"Carried by our nutrition partner. Mixed flavours, 22 g carbohydrate per gel.",
  specs:[["Use","Race fuelling"],["Pack","12 gels"],["Carbs","22 g per gel"]]},
 slide:{n:"Ora Recovery Slide 3",pr:60,c:0,cat:"recovery",color:"Cosmic Blue",
  r:"For the walk to the subway after, and the two days after that.",
  why:"There's roughly 4 km between the NYC finish and your bag, then stairs. This is what you put on the moment you sit down.",
  desc:"A recovery slide with an ultra-cushioned footbed and a soft strap lining.",
  specs:[["Use","Post-run recovery"],["Midsole","Sugarcane EVA"],["Fit","True to size"]]},
 comp:{n:"Recovery Compression Sock",pr:34,c:4,cat:"recovery",color:"Black",
  r:"Worn the evening after, for the flight or the desk on Monday.",
  why:"You booked the Monday off after Chicago. These are for that day, and for the evening after the race.",
  desc:"A graduated compression sock for post-race recovery and travel.",
  specs:[["Use","Recovery and travel"],["Compression","Graduated, 20–30 mmHg"]]},
 hoodie:{n:"Finisher Hoodie",pr:110,c:2,cat:"recovery",color:"Slate",
  r:"Something warm at the finish, 4 km from your bag.",
  why:"Your bag is a long walk from the finish line in Central Park. This is the layer you want waiting in it.",
  desc:"A heavyweight brushed-back hoodie with a relaxed fit.",
  specs:[["Use","Post-race and rest days"],["Fabric","Brushed fleece"]]},
 shell:{n:"Skyflow Waterproof Shell",pr:180,c:2,cat:"apparel",color:"Storm",
  r:"Most trail races require a taped-seam shell on the kit list.",
  why:"It's on the mandatory kit list for this race, and the forecast means you'll actually wear it.",
  desc:"A packable waterproof shell with fully taped seams and an adjustable hood.",
  specs:[["Use","Wet-weather trail"],["Waterproofing","Taped seams"],["Packed size","Fits a vest pocket"]]},
 vest:{n:"Skyflow 5L Vest",pr:125,c:3,cat:"accessories",color:"Storm",
  r:"Carries the mandatory kit and two soft flasks.",
  why:"Five litres is the sweet spot for a trail half with a kit list — shell, food, two flasks, nothing swinging.",
  desc:"A 5-litre race vest with dual front flask pockets and a stretch rear compartment.",
  specs:[["Use","Trail racing"],["Capacity","5 litres"],["Flasks","Two front pockets"]]}};

const CL={road:[
 {h:"To replace the Clifton 10 before race week",s:"480 miles, three long runs left. New shoes want 30 miles before you race in them.",cat:"shoes",i:["clifton11","arahi8","rocketx"]},
 {h:"For a 9°C start and an hour in the corral",s:"From the November forecast and what you wore at Chicago.",cat:"apparel",i:["singlet","longsleeve","gloves"]},
 {h:"The things people forget",s:"Small, cheap, and painful to discover at 30 km.",cat:"accessories",i:["belt","chafe","socks"]},
 {h:"For the Monday after",s:"You booked the day off after Chicago. Same again.",cat:"recovery",i:["slide","comp","hoodie"]}],
trail:[
 {h:"For a wet, technical course",s:"Your Speedgoat is at 95 miles and it's rain all weekend.",cat:"shoes",i:["speedgoat","rockettrail"]},
 {h:"Mandatory kit, mostly",s:"Most trail races check for a shell and a way to carry fluid.",cat:"apparel",i:["shell","vest"]},
 {h:"For the descent and the aftermath",s:"Wet feet, long downhills, cold finish.",cat:"recovery",i:["socks","slide"]}]};

const CHECK=[{k:"shoes",t:"Shoes",d:"Trainer at end of life. Race pair ready.",need:1},
 {k:"apparel",t:"Apparel",d:"Nothing yet for a 9°C start.",need:2},
 {k:"accessories",t:"Accessories",d:"Belt, balm, spare socks.",need:2},
 {k:"nutrition",t:"Nutrition",d:"Race day plus the last long run.",need:1},
 {k:"recovery",t:"Recovery",d:"The 48 hours after the finish.",need:1}];

const STORES=[
 {n:"HOKA 579 Fifth Avenue",t:"Owned store · 4.2 km",live:true,f:"live inventory"},
 {n:"Fleet Feet · Columbus Circle",t:"Partner · 5.1 km",live:false,f:"checked 2 min ago"},
 {n:"JackRabbit · Union Square",t:"Partner · 3.4 km",live:false,f:"checked 3 min ago"},
 {n:"Dick's Sporting Goods · 34th St",t:"Partner · 6.8 km",live:false,f:"checked 2 min ago"}];

const CAT={shoes:["Shoes","A trainer to carry you through taper, and the race pair you already own."],
 apparel:["Apparel","For a 9°C start, an hour in the corral, and three cold long runs before then."],
 accessories:["Accessories","Small things, all of which hurt to discover at 30 km."],
 nutrition:["Nutrition","Race day plus the last long run, from our nutrition partner."],
 recovery:["Recovery","For the walk to the subway, and the two days after."]};

const GAPC={shoes:["No new trainer","Your Clifton 10 is at 480 miles with three long runs to go."],
 apparel:["Cold start uncovered","9°C at the start, and an hour in the corral before it."],
 accessories:["No anti-chafe","42 km is a long way to find out you needed it."],
 nutrition:["No gels","Eight for the race, four for the last long run."],
 recovery:["Nothing for after","You booked the Monday off after Chicago."]};
